name       : python-txaio
version    : 22.2.1
release    : 5
source     :
    - https://github.com/crossbario/txaio/archive/refs/tags/v22.2.1.tar.gz : c5ab9c4401fa324df04a7a0b6c6f16ef057c2c657c457e978c6021d8c594ab8f
homepage   : https://github.com/crossbario/txaio
license    : MIT
component  : programming.python
summary    : Compatibility API between asyncio/Twisted/Trollius
description: |
    txaio is a helper library for writing code that runs unmodified on both Twisted and asyncio/Trollius. This is like six, but for wrapping over differences between Twisted and asyncio so one can write code that runs unmodified on both (aka source code compatibility). In other words: your users can choose if they want asyncio or Twisted as a dependency.
builddeps  :
    - python-mock # check
    - python-pytest # check
build      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
