name       : python-txaio
version    : 21.2.1
release    : 4
source     :
    - https://github.com/crossbario/txaio/archive/refs/tags/v21.2.1.tar.gz : ca6f62d244ec3581b71c5c1f808a8b4a48f35cc02591b2c7c1eba7970d76cb6c
license    : MIT
component  : programming.python
summary    : Compatibility API between asyncio/Twisted/Trollius
description: |
    Compatibility API between asyncio/Twisted/Trollius
builddeps  :
    - python-mock # check
    - python-pytest # check
setup      : |
    %python3_setup
install    : |
    %python3_install
#check      : |
#    %python3_test pytest3
