name       : python-txaio
version    : 2.10.0
release    : 2
source     :
    - https://files.pythonhosted.org/packages/b8/87/efcae4040c2a0af9c871116a6dbf02ee582b396e6de3797fb30cdcc4a7e4/txaio-2.10.0.tar.gz : 4797f9f6a9866fe887c96abc0110a226dd5744c894dc3630870542597ad30853
license    : MIT
component  : programming.python
summary    : Compatibility API between asyncio/Twisted/Trollius
description: |
    Compatibility API between asyncio/Twisted/Trollius
setup      : |
    %python3_setup
install    : |
    %python3_install
